ProjectsAndAlgorithms/Projects/shopping/shopping_cart/urls.py
from django.urls import path
from . import views

app_name = 'shopping_cart'

urlpatterns = [
    path('add/<int:product_id>', views.addCart, name='add_cart'),
    path('cart', views.cartDetails, name='cart_details'),
    path('remove/<int:product_id>', views.itemRemove, name='item_remove'),
    path('destroy/<int:product_id>', views.removeAll, name='remove_all')
]

ProjectsAndAlgorithms/Projects/shopping/shoptest_app/urls.py
from django.urls import path
from . import views

app_name = 'shop_app'

urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail, name='ProdCatDetail'),
    path('search', views.searchProducts, name='search_products'),
    path('register', views.registrationPage, name='registration_page'),
    path('create', views.createAccount, name='account_creation'),
    path('login', views.loginPage, name='login_page'),
    path('sign_in', views.signIn, name='sign_in'),
    path('logout', views.logOut, name='log_out'),
    path('profile', views.profilePage, name='profile'),
    path('update', views.editProfile, name='update'),
    path('delete', views.accountDelete, name='delete'),
]

goat_app/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('', views.landing_page),
    path('create_user', views.create_user),
    path('sign_in', views.sign_in),
    path('profile', views.profile),
    path('edit_user', views.edit_user),
    path('first_index', views.first_index),
    path('random_match', views.random_match),
    path('second_index', views.second_index),
    path('run_bet_random', views.run_bet_random),
    path('run_bet_custom', views.run_bet_custom),
    path('winner_page', views.winner_page),
    path('random_winner_page', views.random_winner_page),
    path('logout', views.logout),
]

ProjectsAndAlgorithms/Projects/shopping/shopping_cart/models.py
from django.db import models
from shoptest_app.models import Product

# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)
    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)
    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product

ProjectsAndAlgorithms/Projects/shopping/shopping_cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shoptest_app.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.
def personalCart(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def addCart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=personalCart(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id = personalCart(request)
        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart,
        )
        cart_item.save()
    return redirect('shopping_cart:cart_details')

def cartDetails(request, total=0, counter=0, cart_items = None):
    try:
        cart = Cart.objects.get(cart_id=personalCart(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items = cart_items, total = total, counter = counter))

def itemRemove(request, product_id):
    cart = Cart.objects.get(cart_id=personalCart(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('shopping_cart:cart_details')

def removeAll(request, product_id):
    cart = Cart.objects.get(cart_id=personalCart(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('shopping_cart:cart_details')

ProjectsAndAlgorithms/Projects/shopping/shopping_cart/templates/cart.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}
This is the page that belongs to your shopping cart. Please review your items and place an order.
{% endblock %}
{% block title %}
Cart - TheUpperHand
{% endblock %}

{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center cart_title">Your shopping cart is empty.</h1>
        <br>
        <p class="text-center">Please Click <a href="{% url 'shop_app:allProdCat' %}">here </a>to view more products.</p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center cart_title">Your shopping cart</h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg6 text-center">
        <table class="table personal-table">
            <thead class="personal-thead">
                <tr>
                    <th colspan="5">
                        Your Items
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href="{{cart_item.product.get_absolute_url}}"><img src="{{cart_item.product.image.url}}"
                                alt="" class="float-left rounded custom-image"></a>
                    </td>
                    <td class="text-left">{{cart_item.product.name}}
                        <br>
                        SKU: {{cart_item.product.id}}
                        <br>
                        Unit Price: ${{cart_item.product.price}}
                        <br>
                        Qty: {{cart_item.quantity}} x ${{cart_item.product.price}}
                    </td>
                    <td>
                        ${{cart_item.sub_total}}
                    </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        <a href="{% url 'shopping_cart:add_cart' cart_item.product.id %}" class="custom-link"><i
                                class="fas fa-plus-circle custom-icon"></i></a>&nbsp;
                        <a href="{% url 'shopping_cart:item_remove' cart_item.product.id %}" class="custom-link"><i
                                class="fas fa-minus-circle custom-icon"></i></a>&nbsp;
                        <a href="{% url 'shopping_cart:remove_all' cart_item.product.id %}" class="custom-icon"><i
                                class="fas fa-eraser custom-icon"></i></a>
                    </td>
                    {% else %}
                    <td>
                        &nbsp;<a href="{% url 'shopping_cart:item_remove' cart_item.product.id %}"
                            class="custom-link"><i class="fas fa-minus-circle custom-icon"></i></a>&nbsp;
                        <a href="{% url 'shopping_cart:remove_all' cart_item.product.id %}" class="custom-icon"><i
                                class="fas fa-eraser custom-icon"></i></a>
                    </td>
                    <td></td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table personal-table">
            <thead class="personal-thead">
                <tr>
                    <th>
                        Checkout
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        Please review your shopping cart before payment.
                    </td>
                </tr>
                <tr>
                    <td class="text-left">
                        Your total is: <strong>${{ total }}</strong>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'shop_app:allProdCat' %}" class="btn btn-secondary btn-block custom-button">Continue shopping</a>
        </div>
    </div>
</div>
<br>
{% endif %}
{% endblock %}