ProjectsAndAlgorithms/Projects/shopping/shopping_cart/urls.py
from django.urls import path
from . import views

app_name = 'shopping_cart'

urlpatterns = [
    path('add/<int:product_id>', views.addCart, name='add_cart'),
    path('cart', views.cartDetails, name='cart_details'),
    path('remove/<int:product_id>', views.itemRemove, name='item_remove'),
    path('destroy/<int:product_id>', views.removeAll, name='remove_all')
]

ProjectsAndAlgorithms/Projects/shopping/shoptest_app/urls.py
from django.urls import path
from . import views

app_name = 'shop_app'

urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail, name='ProdCatDetail'),
    path('search', views.searchProducts, name='search_products'),
    path('register', views.registrationPage, name='registration_page'),
    path('create', views.createAccount, name='account_creation'),
    path('login', views.loginPage, name='login_page'),
    path('sign_in', views.signIn, name='sign_in'),
    path('logout', views.logOut, name='log_out'),
    path('profile', views.profilePage, name='profile'),
    path('update', views.editProfile, name='update'),
    path('delete', views.accountDelete, name='delete'),
]

goat_app/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('', views.landing_page),
    path('create_user', views.create_user),
    path('sign_in', views.sign_in),
    path('profile', views.profile),
    path('edit_user', views.edit_user),
    path('first_index', views.first_index),
    path('random_match', views.random_match),
    path('second_index', views.second_index),
    path('run_bet_random', views.run_bet_random),
    path('run_bet_custom', views.run_bet_custom),
    path('winner_page', views.winner_page),
    path('random_winner_page', views.random_winner_page),
    path('logout', views.logout),
]

ProjectsAndAlgorithms/Projects/shopping/shoptest_app/models.py
from django.db import models
from django.urls import reverse
import bcrypt
import re

class UserManager(models.Manager):
    def registration_validator(self, postData):
        errors = {}
        existing_users = User.objects.filter(username=postData['username'])
        EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

        if len(postData['first_name']) < 2:
            errors['first_name'] = "Your first name should be at least 2 characters with only letters"
        if len(postData['last_name']) < 2:
            errors['last_name'] = "Your last name should be at least 2 characters with only letters"
        if len(postData['email']) == 0:
            errors['email'] = "You must enter an email"
        if not EMAIL_REGEX.match(postData['email']):
            errors['email'] = "The email address is not in the correct format"
        if len(existing_users) != 0:
            errors['username'] = "Your username that you have chosen cannot be used"
        if len(postData['password']) == 0:
            errors['password'] = "Your password cannot be blank."
        if len(postData['password']) < 8:
            errors['password'] = "Your password should be at least 8 characters"
        if (postData['password'] != postData['confirm']):
            errors['confirm'] = "Your passwords do not match"
        return errors

    def login_validator(self, postData):
        errors = {}
        existing_users = User.objects.filter(username=postData['login_username'])

        if len(postData['login_username']) == 0:
            errors ['login_username'] = "Your username needs to be entered"
        if len(postData['login_pass']) == 0:
            errors ['login_pass'] = "Your password needs to be entered"
        if len(postData['login_pass']) < 8:
            errors ['login_pass'] = "An eight character password must be entered"
        if not existing_users:
            errors ['login_pass'] = "Incorrect username or password (not user)"
        elif bcrypt.checkpw(postData['login_pass'].encode(), existing_users[0].password.encode()) != True:
            errors ['login_pass'] = "Incorrect username or password (password)"
        return errors

    def edit_validator(self, postData):
        errors = {}
        existing_users = User.objects.filter(email=postData['email_edit'])
        EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

        if len(postData['email_edit']) < 1:
            errors['email_edit'] = "You must enter a longer email"
        if not EMAIL_REGEX.match(postData['email_edit']):
            errors['email_edit'] = "The email address is not in the correct format"
        if len(existing_users) != 0:
            errors['email_edit'] = "Your email that you have chosen cannot be used"
        if len(postData['password_edit']) < 1:
            errors ['password_edit'] = "A longer password needs to be entered"
        if len(postData['password_edit']) < 8:
            errors ['password_edit'] = "An eight character password must be entered"
        if (postData['password_edit'] != postData['password_editverify']):
            errors['password_editverify'] = "Your passwords do not match"
        return errors
class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)
    #product.category
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shop_app:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        ordering =('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('shop_app:ProdCatDetail', args=[self.category.slug, self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class User(models.Model):
    username = models.CharField(max_length=255, default=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    date_of_birth = models.DateTimeField(null=True)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

    def __repr__(self):
        return f"<User object: {self.username} ({self.id})>"

ProjectsAndAlgorithms/Projects/shopping/shoptest_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.db.models import Q
import bcrypt


# Category View
# Retrieve Category objects
def allProdCat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug = c_slug)
        products_list = Product.objects.filter(category = c_page, available = True)
    else:
        products_list = Product.objects.all().filter(available = True)
    # PAGINATION web pages for products
    paginator = Paginator(products_list, 3)
    try:
        page = int(request.GET.get('page','1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)
    # Checks for user_id in request.session
    login_check = ""
    if 'user_id' in request.session:
        login_check = User.objects.get(id=request.session['user_id'])
    context = {
        'category':c_page,
        'products':products,
        'current_user':login_check
    }
    return render(request, 'struct/category.html', context)

# Product Details
def ProdCatDetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    context = {
        'product':product
    }
    return render(request, 'struct/product.html', context)

# Search Function
def searchProducts(request):
    if request.method == 'POST':
        product_scan = request.POST['product_scan']
        search_results = Product.objects.all().filter(Q(name__contains=product_scan) or Q(description__contains=product_scan))
    context = {
        'product_scan':product_scan,
        'search_results':search_results
    }
    return render(request, 'search.html', context)

# Registration Page
def registrationPage(request):
    return render(request, 'struct/register.html')

# Profile Page
def profilePage(request):
    if 'user_id' not in request.session:
        return redirect('/')
    # Checks for user_id in request.session
    if 'user_id' in request.session:
        login_check = User.objects.get(id=request.session['user_id'])
    context = {
        'current_user':login_check
    }
    return render(request, 'struct/profile.html', context)

# Update Profile Page
def editProfile(request):
    if 'user_id' not in request.session:
        return redirect('/')
    errors = User.objects.edit_validator(request.POST)
    if len(errors) > 0:
        for key, value in errors.items():
            messages.error(request, value)
        return redirect('/profile')
    else:
        # Checks for user_id in request.session
        if 'user_id' in request.session:
            profile_edit = User.objects.get(id=request.session['user_id'])
    profile_password = profile_edit.password
    profile_password = request.POST['password_edit']
    profile_edit.email = request.POST['email_edit']
    profile_passwordHash = bcrypt.hashpw(profile_password.encode(), bcrypt.gensalt()).decode()
    profile_edit.password = profile_passwordHash
    profile_edit.save()
    return redirect('/profile')

# Account Creation
def createAccount(request):
    if request.method != 'POST':
        return redirect('/')
    errors = User.objects.registration_validator(request.POST)
    if len(errors) > 0:
        for key, value in errors.items():
            messages.error(request, value)
        return redirect('/register')
    else:
        new_password = request.POST['password']
        new_passwordHash = bcrypt.hashpw(new_password.encode(), bcrypt.gensalt()).decode()
        new_user = User.objects.create(
            first_name = request.POST['first_name'],
            last_name = request.POST['last_name'],
            email = request.POST['email'],
            username = request.POST['username'],
            password = new_passwordHash,
        )
        request.session['user_id'] = new_user.id
        return redirect('shop_app:allProdCat')

# Login Page
def loginPage(request):
    return render(request, 'struct/login.html')

# Login Function
def signIn(request):
    if request.method != 'POST':
        return redirect('/')
    errors = User.objects.login_validator(request.POST)
    if len(errors) > 0:
        for key, value in errors.items():
            messages.error(request, value)
        return redirect('/login')
    logged_in = User.objects.filter(username=request.POST['login_username'])
    request.session['user_id'] = logged_in[0].id
    return redirect('/')

# Log Out
def logOut(request):
    request.session.flush()
    return redirect('/')

# Delete Account
def accountDelete(request):
    if 'user_id' not in request.session:
        return redirect('/')
    destroy = User.objects.get(id=request.session['user_id'])
    destroy.delete()
    request.session.flush()
    return redirect('/')

ProjectsAndAlgorithms/Projects/shopping/shoptest_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{% block metadescription %} {% endblock metadescription %}">
    <link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/solid.css' %}">
    <title>{% block title %}Welcome to TheUpperHand{% endblock %}</title>
</head>

<body>
    <div class="container">
        {% include 'header.html' %}
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock %}
    </div>
    {% include 'footer.html' %}

    <script src="{% static 'js/jquery-3.6.0.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

</html>

ProjectsAndAlgorithms/Projects/shopping/shoptest_app/templates/footer.html
<div class="footer navbar-fixed-bottom the-footer">
    <p class="text-center">&copy; TheUpperHand Website. All Rights Reserved</p>
</div>

ProjectsAndAlgorithms/Projects/shopping/shoptest_app/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'shop_app:allProdCat' %}"><img src="{% static 'img/logo.png' %}" alt="Software Store"></a>
    </center>
</header>

ProjectsAndAlgorithms/Projects/shopping/shoptest_app/templates/login.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}
    Please login so you have full access to the website
{% endblock %}
{% block title %}
    Login Page
{% endblock %}

{% block content %}
<div class="container">
    <div class="d-flex justify-content-center h-100">
        <div class="card">
            <div class="card-header">
                <h3>Sign In</h3>
            </div>
            <div class="card-body">
                <form>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" class="form-control" placeholder="username">
                    </div>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        <input type="password" class="form-control" placeholder="password">
                    </div>
                    <div class="row align-items-center remember">
                        <input type="checkbox">Remember Me
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Login" class="btn float-right login_btn">
                    </div>
                </form>
            </div>
            <div class="card-footer">
                <div class="d-flex justify-content-center links">
                    Dont have an account?<a href="#">Sign Up</a>
                </div>
                <div class="d-flex justify-content-center">
                    <a href="#">Forgot your password?</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ProjectsAndAlgorithms/Projects/shopping/shoptest_app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown {% if 'shop' in request.path %}active{% endif %}">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false"></a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'shop_app:allProdCat' %}">All Products</a>
                    {% for category in links %}
                    <a class="dropdown-item" href="{{ category.get_url}}">{{category.name}}</a>
                    {% endfor %}
                    <div class="dropdown-divider">
                    </div>
                </div>
            </li>
            {% if item_count > 0 %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'shopping_cart:cart_details' %}"><i
                        class="fas fa-shopping-cart"></i><span class="sr-only">(current)</span>({{item_count}})</a>
            </li>
            {% endif %}
            {% if 'user_id' not in request.session %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'shop_app:login_page' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">|</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'shop_app:registration_page' %}">Create Account</a>
            </li>
            {% endif %}
            {% if 'user_id' in request.session %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'shop_app:log_out' %}">Log Out</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'shop_app:profile' %}">{{current_user.username}}</a>
            </li>
        </ul>

        <form class="form-inline my-2 my-lg-0" method="POST" action="{% url 'shop_app:search_products' %}">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="Game & Hack search" aria-label="Search"
                name="product_scan">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
        </form>
    </div>
</nav>

ProjectsAndAlgorithms/Projects/shopping/shoptest_app/templates/search.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}
BUY THE SOFTWARE
{% endblock metadescription %}
{% block title %}
NO REALLY BUY THE SOFTWARE
{% endblock %}
{% block content %}
<div class="container">
    {% if product_scan %}
    <div class="row mx-auto">
        {% for product in search_results %}
        <div class="bottom-margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
            <div class="card text-center" style="width: 18rem;">
                <a href="{{product.get_url}}"> <img class="card-img-top category-image" src="{{product.image.url}}"
                        alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>${{product.price}}</p>
                </div>
            </div>
            {% empty %}
            <div class="row mx-auto">
                <p>No results found</p>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}